# Setup
title:               arcinas.info
tagline:             'stuff by lyle arcinas'
description:         'An impersonal website.'
url:                 https://arcinas.info
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lyle Arcinas
  url:               https://arcinas.info
  email:             lyle.arcinas@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
